/**
 * @fileoverview gRPC-Web generated client stub for shacl_validator
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.33.0
// source: shacl_validator.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as shacl_validator_pb from './shacl_validator_pb'; // proto import: "shacl_validator.proto"


export class ShaclValidatorClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorValidate = new grpcWeb.MethodDescriptor(
    '/shacl_validator.ShaclValidator/Validate',
    grpcWeb.MethodType.UNARY,
    shacl_validator_pb.JsoldValidationRequest,
    shacl_validator_pb.ValidationReply,
    (request: shacl_validator_pb.JsoldValidationRequest) => {
      return request.serializeBinary();
    },
    shacl_validator_pb.ValidationReply.deserializeBinary
  );

  validate(
    request: shacl_validator_pb.JsoldValidationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<shacl_validator_pb.ValidationReply>;

  validate(
    request: shacl_validator_pb.JsoldValidationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: shacl_validator_pb.ValidationReply) => void): grpcWeb.ClientReadableStream<shacl_validator_pb.ValidationReply>;

  validate(
    request: shacl_validator_pb.JsoldValidationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: shacl_validator_pb.ValidationReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/shacl_validator.ShaclValidator/Validate',
        request,
        metadata || {},
        this.methodDescriptorValidate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/shacl_validator.ShaclValidator/Validate',
    request,
    metadata || {},
    this.methodDescriptorValidate);
  }

}

