# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

name: "Nabu Tests"
description: "Reusable GitHub Action to run Nabu tests"
# Allow specifying a custom docker image so we can test specific versions
inputs:
  gleaner_image:
    required: true
    description: "Docker image to use for Gleaner"
    default: "internetofwater/gleaner:latest"
  generate_coverage:
    required: false
    description: "Generate coverage report"
    default: "false"

runs:
  using: "composite"

  steps:
  
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        repository: "internetofwater/nabu"

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
    - name: Display Go version
      shell: bash
      run: go version
    - name: Install dependencies
      shell: bash
      run: go get ./cmd/nabu

    - name: Build
      shell: bash
      run: go build -v ./cmd/nabu

    - name: Test with the Go CLI
      shell: bash
      run: |
        if [[ "${{ inputs.generate_coverage }}" == "true" ]]; then
          GLEANER_TEST_IMAGE="${{ inputs.gleaner_image }}" go test ./... -coverprofile=coverage.txt
        else
          GLEANER_TEST_IMAGE="${{ inputs.gleaner_image }}" go test ./...
        fi
