# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

name: "Nabu Tests"
description: "Reusable GitHub Action to run Nabu tests"
# Allow specifying a custom docker image so we can test specific versions
inputs:
  generate_coverage:
    required: false
    description: "Generate coverage report"
    default: "false"

runs:
  using: "composite"

  steps:
  
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24
    - name: Display Go version
      shell: bash
      run: go version
    - name: Install dependencies
      shell: bash
      run: go get ./cmd/nabu

    - name: Build
      shell: bash
      run: go build -v ./cmd/nabu

    - name: Test with the Go CLI
      shell: bash
      run: |
        if [[ "${{ inputs.generate_coverage }}" == "true" ]]; then
          go test ./... -coverprofile=coverage.txt
        else
          go test ./...
        fi
