# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shacl_validator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shacl_validator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15shacl_validator.proto\x12\x0fshacl_validator\"*\n\x17TurtleValidationRequest\x12\x0f\n\x07triples\x18\x01 \x01(\t\"{\n\x0fValidationReply\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12:\n\tShaclType\x18\x03 \x01(\x0e\x32\".shacl_validator.MatchingShaclTypeH\x00\x88\x01\x01\x42\x0c\n\n_ShaclType*>\n\x11MatchingShaclType\x12\x14\n\x10LocationOriented\x10\x00\x12\x13\n\x0f\x44\x61tasetOriented\x10\x01\x32h\n\x0eShaclValidator\x12V\n\x08Validate\x12(.shacl_validator.TurtleValidationRequest\x1a .shacl_validator.ValidationReplyB\x15Z\x13internal/protoBuildb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shacl_validator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023internal/protoBuild'
  _globals['_MATCHINGSHACLTYPE']._serialized_start=211
  _globals['_MATCHINGSHACLTYPE']._serialized_end=273
  _globals['_TURTLEVALIDATIONREQUEST']._serialized_start=42
  _globals['_TURTLEVALIDATIONREQUEST']._serialized_end=84
  _globals['_VALIDATIONREPLY']._serialized_start=86
  _globals['_VALIDATIONREPLY']._serialized_end=209
  _globals['_SHACLVALIDATOR']._serialized_start=275
  _globals['_SHACLVALIDATOR']._serialized_end=379
# @@protoc_insertion_point(module_scope)
