# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

# this file represents all services that
# are used when running nabu examples
# not all of these are required to run nabu
# they are grouped together for convenience

services:

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    environment:
      LOG_LEVEL: debug
    ports:
      - "16686:16686"
      - "4317:4317"

  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   restart: unless-stopped
  #   command: ["server", "/data", "--console-address", ":9001"]
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl --silent --fail http://localhost:9000/minio/health/ready || exit 1"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"

volumes:
  minio_data:
