# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

FROM rust:slim AS builder

WORKDIR /app

# Install dependencies needed for building native C libraries and openssl
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    pkg-config \
    libssl-dev \
    protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY shacl_validator_grpc_rs /app
COPY shacl_validator.proto /shacl_validator.proto
COPY shapes /shapes

# Build in release mode
RUN cargo build --release

FROM debian:bookworm-slim AS runtime

WORKDIR /app

# Install only runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl3 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Copy the built binary from the builder stage
COPY --from=builder /app/target/release/shacl_validator_grpc /app/shacl_validator_grpc
COPY shapes /shapes

ENTRYPOINT ["/app/shacl_validator_grpc"]
