# This is a sample config file for Nabu that points to a Google Cloud Storage bucket

context:
  cache: true
  strict: true
contextmaps:
- file: ./assets/schemaorg-current-https.jsonld
  prefix: https://schema.org/
minio:
  accessKey: "" 
  address: storage.googleapis.com
  bucket: harvest-bucket-dev
  port: 443
  region: us
  secretKey: ""
  ssl: true
prefixes:
- summoned/providera
- prov/providera
- orgs
sparql:
  authenticate: false
  endpoint: http://graphdb:7200
  password: ''
  repository: iow
  username: ''
  upsertbatchsize: 100