minio:
  address: localhost
  port: 9000
  accesskey: amazingaccesskey
  secretkey: amazingsecretkey
  bucket: iow
  region: ""
  ssl: false
context:
  cache: true
  strict: true
contextmaps:
  - prefix: https://schema.org/
    file: ./config/iow/schemaorg-current-https.jsonld
sparql:
  endpoint: http://localhost:7200
  authenticate: false
  username: test
  password: password
  repository: iow
prefixes:
  - test
  - test