minio:
  address: localhost
  port: 9000
  accesskey: minioadmin
  secretkey: minioadmin
  bucket: iow
  region: ""
  ssl: false
context:
  cache: true
  strict: true
contextmaps:
  - prefix: https://schema.org/
    file: ./assets/schemaorg-current-https.jsonld
sparql:
  endpoint: http://localhost:7200
  authenticate: false
  username: test
  password: password
  repository: iow
  batch: 100
prefixes:
  - test
  - test