// Copyright 2025 Lincoln Institute of Land Policy
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: shacl_validator/shacl_validator.proto

package protoBuild

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JsoldValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jsonld        string                 `protobuf:"bytes,1,opt,name=jsonld,proto3" json:"jsonld,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsoldValidationRequest) Reset() {
	*x = JsoldValidationRequest{}
	mi := &file_shacl_validator_shacl_validator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsoldValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsoldValidationRequest) ProtoMessage() {}

func (x *JsoldValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shacl_validator_shacl_validator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsoldValidationRequest.ProtoReflect.Descriptor instead.
func (*JsoldValidationRequest) Descriptor() ([]byte, []int) {
	return file_shacl_validator_shacl_validator_proto_rawDescGZIP(), []int{0}
}

func (x *JsoldValidationRequest) GetJsonld() string {
	if x != nil {
		return x.Jsonld
	}
	return ""
}

// Which shacl file we are in coformance with
type ValidationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationReply) Reset() {
	*x = ValidationReply{}
	mi := &file_shacl_validator_shacl_validator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationReply) ProtoMessage() {}

func (x *ValidationReply) ProtoReflect() protoreflect.Message {
	mi := &file_shacl_validator_shacl_validator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationReply.ProtoReflect.Descriptor instead.
func (*ValidationReply) Descriptor() ([]byte, []int) {
	return file_shacl_validator_shacl_validator_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationReply) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidationReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_shacl_validator_shacl_validator_proto protoreflect.FileDescriptor

const file_shacl_validator_shacl_validator_proto_rawDesc = "" +
	"\n" +
	"%shacl_validator/shacl_validator.proto\x12\x0fshacl_validator\"0\n" +
	"\x16JsoldValidationRequest\x12\x16\n" +
	"\x06jsonld\x18\x01 \x01(\tR\x06jsonld\"A\n" +
	"\x0fValidationReply\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2g\n" +
	"\x0eShaclValidator\x12U\n" +
	"\bValidate\x12'.shacl_validator.JsoldValidationRequest\x1a .shacl_validator.ValidationReplyB\x15Z\x13internal/protoBuildb\x06proto3"

var (
	file_shacl_validator_shacl_validator_proto_rawDescOnce sync.Once
	file_shacl_validator_shacl_validator_proto_rawDescData []byte
)

func file_shacl_validator_shacl_validator_proto_rawDescGZIP() []byte {
	file_shacl_validator_shacl_validator_proto_rawDescOnce.Do(func() {
		file_shacl_validator_shacl_validator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shacl_validator_shacl_validator_proto_rawDesc), len(file_shacl_validator_shacl_validator_proto_rawDesc)))
	})
	return file_shacl_validator_shacl_validator_proto_rawDescData
}

var file_shacl_validator_shacl_validator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shacl_validator_shacl_validator_proto_goTypes = []any{
	(*JsoldValidationRequest)(nil), // 0: shacl_validator.JsoldValidationRequest
	(*ValidationReply)(nil),        // 1: shacl_validator.ValidationReply
}
var file_shacl_validator_shacl_validator_proto_depIdxs = []int32{
	0, // 0: shacl_validator.ShaclValidator.Validate:input_type -> shacl_validator.JsoldValidationRequest
	1, // 1: shacl_validator.ShaclValidator.Validate:output_type -> shacl_validator.ValidationReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shacl_validator_shacl_validator_proto_init() }
func file_shacl_validator_shacl_validator_proto_init() {
	if File_shacl_validator_shacl_validator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shacl_validator_shacl_validator_proto_rawDesc), len(file_shacl_validator_shacl_validator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shacl_validator_shacl_validator_proto_goTypes,
		DependencyIndexes: file_shacl_validator_shacl_validator_proto_depIdxs,
		MessageInfos:      file_shacl_validator_shacl_validator_proto_msgTypes,
	}.Build()
	File_shacl_validator_shacl_validator_proto = out.File
	file_shacl_validator_shacl_validator_proto_goTypes = nil
	file_shacl_validator_shacl_validator_proto_depIdxs = nil
}
