// Copyright 2025 Lincoln Institute of Land Policy
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: shacl_validator/shacl_validator.proto

package protoBuild

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShaclValidator_Validate_FullMethodName = "/shacl_validator.ShaclValidator/Validate"
)

// ShaclValidatorClient is the client API for ShaclValidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShaclValidatorClient interface {
	Validate(ctx context.Context, in *JsoldValidationRequest, opts ...grpc.CallOption) (*ValidationReply, error)
}

type shaclValidatorClient struct {
	cc grpc.ClientConnInterface
}

func NewShaclValidatorClient(cc grpc.ClientConnInterface) ShaclValidatorClient {
	return &shaclValidatorClient{cc}
}

func (c *shaclValidatorClient) Validate(ctx context.Context, in *JsoldValidationRequest, opts ...grpc.CallOption) (*ValidationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationReply)
	err := c.cc.Invoke(ctx, ShaclValidator_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShaclValidatorServer is the server API for ShaclValidator service.
// All implementations must embed UnimplementedShaclValidatorServer
// for forward compatibility.
type ShaclValidatorServer interface {
	Validate(context.Context, *JsoldValidationRequest) (*ValidationReply, error)
	mustEmbedUnimplementedShaclValidatorServer()
}

// UnimplementedShaclValidatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShaclValidatorServer struct{}

func (UnimplementedShaclValidatorServer) Validate(context.Context, *JsoldValidationRequest) (*ValidationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedShaclValidatorServer) mustEmbedUnimplementedShaclValidatorServer() {}
func (UnimplementedShaclValidatorServer) testEmbeddedByValue()                        {}

// UnsafeShaclValidatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShaclValidatorServer will
// result in compilation errors.
type UnsafeShaclValidatorServer interface {
	mustEmbedUnimplementedShaclValidatorServer()
}

func RegisterShaclValidatorServer(s grpc.ServiceRegistrar, srv ShaclValidatorServer) {
	// If the following call pancis, it indicates UnimplementedShaclValidatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShaclValidator_ServiceDesc, srv)
}

func _ShaclValidator_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsoldValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaclValidatorServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaclValidator_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaclValidatorServer).Validate(ctx, req.(*JsoldValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShaclValidator_ServiceDesc is the grpc.ServiceDesc for ShaclValidator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShaclValidator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shacl_validator.ShaclValidator",
	HandlerType: (*ShaclValidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _ShaclValidator_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shacl_validator/shacl_validator.proto",
}
