# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

name: Test shacl_validator_grpc

on:
  push:
    paths:
      - 'shacl_validator/**'
      - '.github/workflows/cargo_test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    defaults:
      run:
        working-directory: shacl_validator/shacl_validator_grpc_rs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            shacl_validator/shacl_validator_grpc_rs -> target
          cache-on-failure: true
          cache-all-crates: true

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Run cargo test
        run: cargo test --all

      - name: Run cargo clippy
        run: cargo clippy --workspace --no-deps --all-targets --all-features -- -D warnings
