# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

name: Test shacl_validator_grpc

on:
  push:
    paths:
      - 'shacl_validator/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2
        with:
          # failure could be caused by clippy and thus we should still cache all the 
          # dependency downloads that are irrelevant to the lint errors
          cache-on-failure: true
          cache-all-crates: true

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Run cargo test in shacl_validator_grpc
        working-directory: ./shacl_validator/shacl_validator_grpc_rs
        run: cargo test --all

      - name: Run cargo clippy in shacl_validator_grpc
        working-directory: shacl_validator/shacl_validator_grpc_rs
        run:  cargo clippy --workspace --no-deps --all-targets --all-features -- -D warnings