# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

name: Test shacl_validator_grpc

on:
  push:
    paths:
      - 'shacl_validator_grpc/**'
  pull_request:
    paths:
      - 'shacl_validator_grpc/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Run cargo test in shacl_validator_grpc
        working-directory: ./shacl_validator_grpc
        run: cargo test --all

      - name: Run cargo clippy in shacl_validator_grpc
        working-directory: ./shacl_validator_grpc
        run:  cargo clippy --workspace --no-deps --all-targets --all-features -- -D warnings