# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

name: Test Full Geoconnex Pipeline

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-temp-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Unique Image Tag
        id: vars
        run: echo "tag=tmp-${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BINARY_NAME=nabu
          context: .
          push: true
          tags: internetofwater/nabu:${{ env.tag }}


      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            BINARY_NAME=gleaner
          context: .
          push: true
          tags: internetofwater/gleaner:${{ env.tag }}

      - name: "Run Geoconnex Scheduler to simulate a full crawl"
        uses: internetofwater/scheduler@main
        with:
          nabu_image: internetofwater/nabu:${{ env.tag }}
          gleaner_image: internetofwater/gleaner:${{ env.tag }}
          