# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

name: Go Lint

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches-ignore:
      - master


jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1

