# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

name: Google S3 Ping Check

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          # don't push the image since we just need it locally to run 
          # the s3 test
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: nabu

      - name: Create Docker Network
        run: docker network create mynetwork

      - name: Run Nabu
        run: |
            docker run --network mynetwork \
            -e S3_ACCESS_KEY=${{ secrets.GOOGLE_S3_ACCESS_KEY }} \
            -e S3_SECRET_KEY=${{ secrets.GOOGLE_S3_SECRET_KEY }} \
            --rm nabu test --port 443 --region us --ssl --bucket harvest-bucket-dev --address storage.googleapis.com 
        