# Copyright 2025 Lincoln Institute of Land Policy
# SPDX-License-Identifier: Apache-2.0

name: Google S3 Ping Check

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches-ignore:
      - master


jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Docker Network
        run: docker network create mynetwork

      - name: Build Nabu Docker Image
        run: docker build --build-arg BINARY_NAME=nabu  -t nabu .

      - name: Run Nabu
        run: |
            docker run --network mynetwork \
            -e S3_ACCESS_KEY=${{ secrets.GOOGLE_S3_ACCESS_KEY }} \
            -e S3_SECRET_KEY=${{ secrets.GOOGLE_S3_SECRET_KEY }} \
            --rm nabu test --port 443 --region us --ssl --bucket harvest-bucket-dev --address storage.googleapis.com 
        