name: Test Nabu Subcommand Options 

on: [push]
 
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Install and Run Nabu Runtime Dependencies, Test Utils, and Setup Env.
        run: |
            echo "::group::Install/Run Nabu Runtime Dependencies"
            mkdir -p $HOME/bin
            sh scripts/cicd/download-mc.sh
            sh scripts/cicd/start-minio.sh
            sh scripts/cicd/start-graphdb.sh 
            echo "::endgroup::"
      - name: Setup Environment
        run: |
            echo "::group::Setup Environment"
            $HOME/bin/mc alias set myminio http://localhost:9000 minioadmin minioadmin
            $HOME/bin/mc mb myminio/iow
            echo "::endgroup::"
      - name: Build Gleaner and Nabu 
        run: |
            echo "::group::Build Gleaner"
            sh scripts/cicd/build-gleaner.sh
            sh scripts/cicd/build-nabu.sh
            echo "::endgroup::" 
      - name: Run Gleaner Harvest To Create Input For Nabu
        run: |
            echo "::group::Run Gleaner Harvest"
            sh scripts/cicd/start-gleaner.sh config/iow/gleanerconfig.yaml
            $HOME/bin/mc ls myminio/iow/prov/refgages0 | grep '.jsonld' | wc -l
            bash scripts/cicd/check-gleaner-s3-output.sh
      - name: Test Nabu Release
        run: |
            echo "::group::Test Nabu Release"
            $HOME/nabu release --cfg config/iow/nabuconfig.yaml  --prefix prov/refgages0
            $HOME/bin/mc cat myminio/iow/graphs/latest/refgages0_prov.nq | wc -l
      - name: Cleanup Environment
        if: ${{ always() }}
        run: |
            sh scripts/cicd/stop-minio.sh
            sh scripts/cicd/stop-graphdb.sh            

