name: Test Nabu Subcommand Options 
on:
  [  workflow_dispatch, pull_request ]
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: Install and Run Nabu Runtime Dependencies, Test Utils, and Setup Env.
        run: |
            echo "::group::Install/Run Nabu Runtime Dependencies"
            mkdir -p $HOME/bin
            curl https://dl.min.io/client/mc/release/linux-amd64/mc -o $HOME/bin/mc && chmod +x $HOME/bin/mc 
            sh scripts/iow/start-minio.sh
            sh scripts/iow/start-graphdb.sh 
            echo "::endgroup::"
      - name: Setup Environment
        run: |
            echo "::group::Setup Environment"
            $HOME/bin/mc alias set myminio http://localhost:9000 amazingaccesskey amazingsecretkey
            $HOME/bin/mc mb myminio/iow
            echo "::endgroup::"
      - name: Build Gleaner 
        run: |
            echo "::group::Build Gleaner"
            mkdir $HOME/build
            cd $HOME/build && git clone https://github.com/internetofwater/gleaner.git
            cd gleaner && make && cp gleaner $HOME/bin
            echo "::endgroup::" 
      - name: Run Gleaner Harvest To Create Input For Nabu
        run: |
            echo "::group::Run Gleaner Harvest"
            sh scripts/iow/start-gleaner.sh config/iow/gleanerconfig.yaml
            $HOME/bin/mc  ls myminio/iow/prov/refgages0|grep '.jsonld'|wc -l
            sh scripts/iow/check-gleaner-s3-output.sh
